// Import the createSlice function from Redux Toolkit
import { createSlice } from '@reduxjs/toolkit';

// Create a new slice of state called 'counter'
const counterSlice = createSlice({
  // Name of the slice
  name: 'counter',
  
  // Initial state of the counter slice
  initialState: {
    value: 0,
  },
  
  // Reducers to define how the state changes
  reducers: {
    // Action to increment the counter
    increment: (state) => {
      state.value += 1;
    },
    // Action to decrement the counter
    decrement: (state) => {
      state.value -= 1;
    },
    // Action to increment the counter by a specific amount
    incrementByAmount: (state, action) => {
      state.value += action.payload;
    },
  },
});

// Export the action creators generated by createSlice
export const { increment, decrement, incrementByAmount } = counterSlice.actions;

// Export the reducer to be used in the store configuration
export default counterSlice.reducer;
